### ISSUE TITLE
errors while running the example of 4iiy.pdb

### ISSUE THREAD

**Issue by MachineGUN001** [HaotianZhangAI4Science/ResGen#8]
hi, haotian,

thanks for your great work.
but when I try to run the example of 4iiy.pdb, the following errors occured.

```bash
Num of parameters is 37.52M
Start to generate in the ./Test/4iiy.pdb
c:\Users\XXT\.conda\envs\Resgen\lib\site-packages\numpy\core\fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\XXT\.conda\envs\Resgen\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3484.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "e:\ResGen-main\gen.py", line 217, in <module>
    rdmol = reconstruct_from_generated_with_edges(data_next)
  File "e:\ResGen-main\utils\reconstruct.py", line 70, in reconstruct_from_generated_with_edges
    Chem.SanitizeMol(rd_mol, Chem.SANITIZE_ALL^Chem.SANITIZE_KEKULIZE^Chem.SANITIZE_SETAROMATICITY)
OverflowError: can't convert negative int to unsigned
```
could you please provide the suggestions how to fix it up?
many thanks,

ShY

**Comment by zhy272711** [comment]
> hi, haotian,
> 
> thanks for your great work. but when I try to run the example of 4iiy.pdb, the following errors occured.
> 
> ```shell
> Num of parameters is 37.52M
> Start to generate in the ./Test/4iiy.pdb
> c:\Users\XXT\.conda\envs\Resgen\lib\site-packages\numpy\core\fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
>   return _methods._mean(a, axis=axis, dtype=dtype,
> c:\Users\XXT\.conda\envs\Resgen\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3484.)
>   return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
> Traceback (most recent call last):
>   File "e:\ResGen-main\gen.py", line 217, in <module>
>     rdmol = reconstruct_from_generated_with_edges(data_next)
>   File "e:\ResGen-main\utils\reconstruct.py", line 70, in reconstruct_from_generated_with_edges
>     Chem.SanitizeMol(rd_mol, Chem.SANITIZE_ALL^Chem.SANITIZE_KEKULIZE^Chem.SANITIZE_SETAROMATICITY)
> OverflowError: can't convert negative int to unsigned
> ```
> 
> could you please provide the suggestions how to fix it up? many thanks,
> 
> ShY

I have the same problem. Have you solved it？

**Comment by MachineGUN001** [comment]
> I think the problem is the conflict of rdkit molecule. Please try to read the rd_mol out of the code, I guess the output is None. To fix this problem, make sure your rdkit is proper. You can transform the .sdf with openbabel, like obabel xxx.sdf -O xxx.sdf (in the command), sometimes, the openbabel can automatically reorder and fix molecular problems. Feel free to contact me if you have any problems!

thanks for your suggestions,

after running openbael to convert .sdf, the error still occured.

```
Namespaces are one honking great idea -- let's do more of those!
Num of parameters is 37.52M
Start to generate in the [./Test/4iiy.pdb](https://file+.vscode-resource.vscode-cdn.net/e%3A/Cheminfo_Workshop/4_Fragment_Scaffold_Evolution/ResGen-main/Test/4iiy.pdb)
[c:\Users\LSY\.conda\envs\TargetDiff\lib\site-packages\numpy\core\fromnumeric.py:3432](file:///C:/Users/LSY/.conda/envs/TargetDiff/lib/site-packages/numpy/core/fromnumeric.py:3432): RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
[c:\Users\LSY\.conda\envs\TargetDiff\lib\site-packages\torch\functional.py:504](file:///C:/Users/LSY/.conda/envs/TargetDiff/lib/site-packages/torch/functional.py:504): UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at [C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3191](file:///C:/actions-runner/_work/pytorch/pytorch/builder/windows/pytorch/aten/src/ATen/native/TensorShape.cpp:3191).)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "gen.py", line 217, in <module>
    rdmol = reconstruct_from_generated_with_edges(data_next)
  File "e:\ResGen-main\utils\reconstruct.py", line 70, in reconstruct_from_generated_with_edges
    Chem.SanitizeMol(rd_mol, Chem.SANITIZE_ALL^Chem.SANITIZE_KEKULIZE^Chem.SANITIZE_SETAROMATICITY)
OverflowError: can't convert negative int to unsigned
```

so I will reinstall the envs and follow the resn.yml in your repo and see if that works.

many thanks,

Best,
ShY

**Comment by MachineGUN001** [comment]
> > hi, haotian,
> > thanks for your great work. but when I try to run the example of 4iiy.pdb, the following errors occured.
> > ```shell
> > Num of parameters is 37.52M
> > Start to generate in the ./Test/4iiy.pdb
> > c:\Users\XXT\.conda\envs\Resgen\lib\site-packages\numpy\core\fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
> >   return _methods._mean(a, axis=axis, dtype=dtype,
> > c:\Users\XXT\.conda\envs\Resgen\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3484.)
> >   return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
> > Traceback (most recent call last):
> >   File "e:\ResGen-main\gen.py", line 217, in <module>
> >     rdmol = reconstruct_from_generated_with_edges(data_next)
> >   File "e:\ResGen-main\utils\reconstruct.py", line 70, in reconstruct_from_generated_with_edges
> >     Chem.SanitizeMol(rd_mol, Chem.SANITIZE_ALL^Chem.SANITIZE_KEKULIZE^Chem.SANITIZE_SETAROMATICITY)
> > OverflowError: can't convert negative int to unsigned
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > could you please provide the suggestions how to fix it up? many thanks,
> > ShY
> 
> I have the same problem. Have you solved it？

not yet, but you can try to check the env yml if that's consistent with the repo.

**Comment by zhy272711** [comment]
Thanks for your reply. I have fixed the problem. Do you need my help?



---Original---
From: ***@***.***&gt;
Date: Mon, Jan 22, 2024 11:19 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HaotianZhangAI4Science/ResGen] errors while running the exampleof 4iiy.pdb (Issue #8)




   
hi, haotian,
 thanks for your great work. but when I try to run the example of 4iiy.pdb, the following errors occured.
 Num of parameters is 37.52M Start to generate in the ./Test/4iiy.pdb c:\Users\XXT\.conda\envs\Resgen\lib\site-packages\numpy\core\fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.   return _methods._mean(a, axis=axis, dtype=dtype, c:\Users\XXT\.conda\envs\Resgen\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3484.)   return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined] Traceback (most recent call last):   File "e:\ResGen-main\gen.py", line 217, in <module&gt;     rdmol = reconstruct_from_generated_with_edges(data_next)   File "e:\ResGen-main\utils\reconstruct.py", line 70, in reconstruct_from_generated_with_edges     Chem.SanitizeMol(rd_mol, Chem.SANITIZE_ALL^Chem.SANITIZE_KEKULIZE^Chem.SANITIZE_SETAROMATICITY) OverflowError: can't convert negative int to unsigned
 
could you please provide the suggestions how to fix it up? many thanks,
 ShY
  
I have the same problem. Have you solved it？
  
not yet, but you can try to check the env yml if that's consistent with the repo.

**Comment by MachineGUN001** [comment]
> Thanks for your reply. I have fixed the problem. Do you need my help?
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Jan 22, 2024 11:19 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [HaotianZhangAI4Science/ResGen] errors while running the exampleof 4iiy.pdb (Issue #8) hi, haotian, thanks for your great work. but when I try to run the example of 4iiy.pdb, the following errors occured. Num of parameters is 37.52M Start to generate in the ./Test/4iiy.pdb c:\Users\XXT\.conda\envs\Resgen\lib\site-packages\numpy\core\fromnumeric.py:3464: RuntimeWarning: Mean of empty slice. return _methods._mean(a, axis=axis, dtype=dtype, c:\Users\XXT\.conda\envs\Resgen\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3484.) return _VF.meshgrid(tensors, **kwargs) # type: ignore[attr-defined] Traceback (most recent call last): File "e:\ResGen-main\gen.py", line 217, in <module&gt; rdmol = reconstruct_from_generated_with_edges(data_next) File "e:\ResGen-main\utils\reconstruct.py", line 70, in reconstruct_from_generated_with_edges Chem.SanitizeMol(rd_mol, Chem.SANITIZE_ALL^Chem.SANITIZE_KEKULIZE^Chem.SANITIZE_SETAROMATICITY) OverflowError: can't convert negative int to unsigned could you please provide the suggestions how to fix it up? many thanks, ShY I have the same problem. Have you solved it？ not yet, but you can try to check the env yml if that's consistent with the repo. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

how can you fix the problem? I still cannot run the Chem.SanitizeMol code. 
many thanks,

best,
